### ISSUE TITLE
more details about the register definition

### ISSUE THREAD

**Issue by rill-zhen** [nvdla/doc#2]
thanks so mush for sharing NVDLA. 
i read the register description carefully,and found that there is only a few vivid words for key points, what should i do if i want to integrate NVDLAinto my design(the integration)? 
where can i find the details about "loadable image"?

**Comment by jwise** [comment]
Oops, missed this ticket on the doc repo.

Our initial release is to help people get started integrating the IP, but it's true that our register specification is not fully documented yet.  You should be able to integrate NVDLA's RTL interfaces at this stage, and use the traces from the trace-player test bench to validate that integration with your system; we'll have more info coming soon on software drivers, and on how to compile networks (and generate a loadable image).
